### ISSUE TITLE
Gruntfile.js没有起作用

### ISSUE THREAD

**Issue by blankyao** [edokeh/spm-chaos-build#2]
在用[seajs-rails](https://github.com/edokeh/seajs-rails)这个Gem时发现的，在编译后没生成map文件，于是顺着代码查了下，最后发现是在用spm-chaos-build编译时Gruntfile.js没起作用，直接到js目录下去执行spm-chaos-build也不行，只执行到了index.js里定义的[taskList](https://github.com/edokeh/spm-chaos-build/blob/master/index.js#L18)里面定义的task，有遇到过这个情况的不？

版本：
spm 2.1.2
spm-chaos-build 0.2.2

**Comment by edokeh** [comment]
1. 清空 public/assets 目录（不要删除它）
2. 执行 `rake seajs:compile:prepare_dir` ，检查目录是不是已经被拷贝了，public/assets 目录下有没有 Gruntfile.js
3. 执行 `rake seajs:compile:generate_json`，检查有没有生成 public/assets/javascripts/package.json
4. 到 public/assets 目录下，执行 `spm chaos-build javascripts`

你顺序执行以上四步，看看哪一步有问题
从你的描述里面看，貌似有个地方不对，不应当是到 js 目录下，而是到 public/assets 目录下执行

**Comment by edokeh** [comment]
突然想起来了，你是不是在 Ubuntu 上用 Cap 执行的？
Cap 有个问题，他不会载入系统的变量，所以执行 Node.js 的程序时，无法载入 npm 的包

如果不是的话，我猜你的问题可能也与此类似，你可以试试执行这个命令 `node -e 'console.log(process.env.NODE_PATH)'` ，看看有没有输出

参考我的 cap 脚本 https://github.com/edokeh/klog/blob/master/config/deploy.rb#L17

**Comment by blankyao** [comment]
果然是这个原因，我在mac上用brew安装的node，没配置环境变量，多谢@edokeh

**Comment by edokeh** [comment]
呵呵，看来这是个通病啊，我回头补到文档里面去
