### ISSUE TITLE
打包之后的文件貌似不能跑

### ISSUE THREAD

**Issue by despairlin** [edokeh/spm-chaos-build#3]
看了seajs的文档，"define(function(require));"中的require不是不能改变吗？压缩之后，变成了字母“e”，会报错的~请问你们的文件能正常运作吗？顺便问一下，package.json中的alias的路径是相对哪里的？

**Comment by edokeh** [comment]
压缩后是可以改变的，但是压缩完了以后模块的格式需要是 define(id, depts, fn)
package.json 里面的 alias 是配置压缩合并时候的策略的，参考 grunt-cmd-transport
