### ISSUE TITLE
win xp 32位系统安装失败

### ISSUE THREAD

**Issue by gyf19** [edokeh/spm-chaos-build#4]
> npm install spm -g //安装顺利
> npm install spm-chaos-build -g  //错误分三段，分别贴出来 

npm http GET https://registry.npmjs.org/iconv-lite
npm http 200 https://registry.npmjs.org/grunt
npm ERR! Error: ENOENT, lstat 'C:\Documents and Settings\xxxxxxx\ApplicationData\npm\node_modules\spm-chaos-build\node_modules\grunt\AUTHORS'
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com
npm ERR! System Windows_NT 5.1.2600
npm ERR! command "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "spm-chaos-build" "-g"
npm ERR! cwd D:\
npm ERR! node -v v0.8.18
npm ERR! npm -v 1.2.2
npm ERR! path C:\Documents and Settings\xxxxxxx\Application Data\npm\node_modules\spm-chaos-build\node_modules\grunt\AUTHORS
npm ERR! fstream_path C:\Documents and Settings\xxxxxxx\Application Data\npm\node_modules\spm-chaos-build\node_modules\grunt\AUTHORS
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack C:\Program Files\nodejs\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:297:15)
npm ERR! error rolling back Error: EPERM, rmdir 'C:\Documents and Settings\xxxxxxx\Application Data\npm\node_modules\spm-chaos-build\node_modules\grunt\test'
npm ERR! error rolling back  grunt@0.4.1 { [Error: EPERM, rmdir 'C:\Documents and Settings\xxxxxxx\Application Data\npm\node_modules\spm-chaos-build\node_modules\grunt\test']
npm ERR! error rolling back   errno: 50,
npm ERR! error rolling back   code: 'EPERM',
npm ERR! error rolling back   path: 'C:\Documents and Settings\xxxxxxx\Application Data\npm\node_modules\spm-chaos-build\node_modules\grunt\test' }
npm http 304 https://registry.npmjs.org/uglify-js
npm http GET https://registry.npmjs.org/hooker

.....

npm ERR! error rolling back Error: EBUSY, unlink 'C:\Documents and Settings\xxxxxxx\Application Data\npm\node_modules\spm-chaos-build'
npm ERR! error rolling back  spm-chaos-build@0.2.3 { [Error: EBUSY, unlink 'C:\Documents and Settings\xxxxxxx\Application Data\npm\node_modules\spm-chaos-build']
npm ERR! error rolling back   errno: 10,
npm ERR! error rolling back   code: 'EBUSY',
npm ERR! error rolling back   path: 'C:\Documents and Settings\xxxxxxx\Application Data\npm\node_modules\spm-chaos-build' }
npm ERR! Error: EPERM, rmdir 'C:\Documents and Settings\xxxxxxx\Application Data\npm\node_modules\spm-chaos-build\node_modules\grunt\test\fixtures\expand\js'
npm ERR!  { [Error: EPERM, rmdir 'C:\Documents and Settings\xxxxxxx\Application Data\npm\node_modules\spm-chaos-build\node_modules\grunt\test\fixturesexpand\js']
npm ERR!   errno: 50,
npm ERR!   code: 'EPERM',
npm ERR!   path: 'C:\Documents and Settings\xxxxxxx\Application Data\npm\node_modules\spm-chaos-build\node_modules\grunt\test\fixtures\expand\js' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.
npm ERR! System Windows_NT 5.1.2600
npm ERR! command "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "spm-chaos-build" "-g"
npm ERR! cwd D:\
npm ERR! node -v v0.8.18
npm ERR! npm -v 1.2.2
npm ERR! path C:\Documents and Settings\xxxxxxx\Application Data\npm\node_modules\spm-chaos-build\node_modules\grunt\test\fixtures\expand\js
npm ERR! code EPERM
npm ERR! errno 50
npm ERR! stack Error: EPERM, rmdir 'C:\Documents and Settings\xxxxxxx\Application Data\npm\node_modules\spm-chaos-build\node_modules\grunt\test\fixtures\expand\js'
npm http 304 https://registry.npmjs.org/argparse

.....

npm http 304 https://registry.npmjs.org/underscore
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     D:\npm-debug.log
npm ERR! not ok code 0

**Comment by edokeh** [comment]
好的，我去找个 winxp 来试试

**Comment by edokeh** [comment]
@gyf19 
你的 node 版本是 0.8 吗？
试试 0.10.x 的版本看看？

**Comment by gyf19** [comment]
我的 node 版本是 v0.8.18 。  我试试 0.10.x 版本

**Comment by edokeh** [comment]
公司暂时找不到 winxp 的虚拟机，只能晚上回家试试了

**Comment by gyf19** [comment]
我试过了 0.10.x 版本可以安装成功。

**Comment by gyf19** [comment]
明天我再试试spm-chaos-build 功能。  谢谢楼主

**Comment by edokeh** [comment]
不客气，那可能是 node 版本上的不兼容
我回头看看 win7 上是不是也这样，如果是的话，我会在 pacakge.json 里加上相应的 engine 的限制

**Comment by edokeh** [comment]
试了下确实是与 node 0.8 不兼容，应该是某个依赖包的问题

**Comment by gyf19** [comment]
楼主   太敬业了。   谢谢。  如果以后有spm2问题，还需要麻烦您。   先谢了

**Comment by edokeh** [comment]
不客气，issue 我先关了
