### ISSUE TITLE
什么情况下会、报‘ error: Unable to parse "portal/package.json" file (Unexpected token ])’的错误？

### ISSUE THREAD

**Issue by davidHuanghw** [edokeh/spm-chaos-build#7]
我的package.json的内容如下：
{
    "spm" : {
        "output" : {
            "relative" : [
                "standard/main.js",
            ],
            "all" : [
                "base/book_common.js",
                "base/middleware.js",
                "base/uti.js"
            ]
        },
        "alias": {
          "underscore": "gallery/underscore/1.5.2/underscore",
          "backbone": "gallery/backbone/1.1.0/backbone"
        },
    }
}

有base和standard两个目录。base目录下有book_common.js,middleware.js,util.js三个文件。standard下有main.js和standard.js2个文件。

执行 命令spm chaos-build portal -C seajs-config.js报错：
error: Unable to parse "portal/package.json" file (Unexpected token ])

请教下是哪里配置问题？谢谢。

**Comment by davidHuanghw** [comment]
spm2不支持数组或对象属性末尾带","的吗？只要带最后一个元素带","就会报以上错误。

**Comment by edokeh** [comment]
不是 spm2，是 JSON 格式不支持末尾多一个“,”
在 Node.js 里面这么写就会报错
