### ISSUE TITLE
为什么会报 error: Cannot read property 'handlebars' of ~ 的错误

### ISSUE THREAD

**Issue by davidHuanghw** [edokeh/spm-chaos-build#8]
执行命令时报错
spm chaos-build portal -C portal-config.js
错误内容：
 error: Cannot read property 'handlebars' of ~ 
但是代码中并无用到handlebars。也无依赖handlebars的库。

**Comment by davidHuanghw** [comment]
如果package.json没有声明alias属性，就会报此错误。我认为这是个bug。为什么一定要有alias属性呢？只好将alias属性设置为空对象。建议作者修复此问题。

**Comment by edokeh** [comment]
呃，好的我来看看，你重开一下吧

**Comment by edokeh** [comment]
已修复 @davidHuanghw
