### ISSUE TITLE
终于打包成功了。但是应用到具体项目中却无法执行，悲催了

### ISSUE THREAD

**Issue by davidHuanghw** [edokeh/spm-chaos-build#9]
以下是我打包成功的文件内容：

define("portal/standard/main", ["./standard", "../base/book_common", "../base/middleware", "../base/util"], function(a) {
    var t = a("./standard");
    t.init()
}), define("portal/standard/standard", ["portal/base/book_common", "portal/base/middleware", "portal/base/util"], function(a, t, e) {
    function o(a, t) {
        var e;
        if ("zip" == a) {
            var o = $("#bookID").val(), e = {
                uploadScript : "/Portal/File/uploadZip?bookID=" + o,
                multi : !1,
                removeCompleted : !1,
                fileObjName : "Zip Files",
                buttonText : "Upload",
                width : 100,
                formData : {
                    PHPSESSID : "<?php echo session_id(); ?>"
                },
                fileSizeLimit : "600MB",
                fileType : ["zip", "7z"],
                buttonClass : "standardUploadBg",
                onUploadComplete : function(a, t) {
                    if (!t)
                        return showError("Upload Failed"), !1;
                    var t = JSON.parse(t), e = $("#scaleSel").val(), i = {
                        bookID : o,
                        fileID : t.fileID,
                        scale : e
                    };
                    $.post("/Portal/Plan/saveStandardBook", i, function(a) {
                        a.status ? showSuccessAndRefresh(a.info) : showError(a.info)
                    }, "json")
                }
            };
            $("#" + t).uploadifive(e), $("#uploadifive-" + t).attr("title", "Upload File").css("cursor", "pointer").on("click", function(a) {
                var t = $("#issueStatus").val();
                "published" == t && (confirm("當前Issue已經發布，是否繼續操作?") || (a.preventDefault(), a.stopPropagation()))
            })
        }
    }

```
function i() {
    $("#editBookBtn").on("click", r), $(".closeBtn").on("click", l)
}

function r() {
    n()
}

function n() {
    p.showMask(), $("#right-panel").panel("open"), $("#planForm").show()
}

function l() {
    $("#right-panel").panel("close"), $("#maskLayer").hide()
}

var s = a("portal/base/book_common"), d = a("portal/base/middleware"), p = a("portal/base/util");
e.exports = {
    init : function() {
        i(), d.subscribe("closePanel", l), o("zip", "uploadStandardBtn"), s.init()
    }
}
```

}), define("portal/base/book_common", ["portal/base/middleware", "portal/base/util"], function(a, t, e) {
    function o() {
        var a = $("#libraryFilterList"), t = $("#libraryFilter");
        $("#filterAutocomplete").on("listviewbeforefilter", function(a, e) {
            var o = $(this), i = $(e.input).val(), r = "";
            t.val(""), o.html(""), i && i.length > 1 && (o.html("<li><div class='ui-loader'><span class='ui-icon ui-icon-loading'></span></div></li>"), o.listview("refresh"), $.post("/Portal/Plan/getFilters", {
                content : i,
                issueID : $("#plan_issueID").val()
            }).then(function(a) {
                if (a.status) {
                    var t = a.data;
                    t && ($.each(t, function(a, t) {
                        r += "<li><a href=# filterID=" + t.id + ">" + t.filter + "</a></li>"
                    }), o.html(r), o.listview("refresh"), o.trigger("updatelayout"))
                } else
                    a.info == f.TIPS.timeout ? showErrorAndRefresh(f.TIPS.timeoutInfo, a.data) : showError(a.info)
            }))
        }).on("click", "li", function(e) {
            var o = $(e.target).html();
            a.find("input").val(o), t.val(o), $("#filterAutocomplete").empty()
        }), a.find("span.ui-btn-inner").on("mousedown touchend", function() {
            t.val("")
        })
    }

```
function i(a) {
    if (f.stopBubble(a), $("div.error").removeClass("error"), $("div.errorWrap").empty(), n()) {
        if (!$("#plan_issueID").val())
            return showError("No issueID!"), !1;
        if ($("#libraryFilter").val($("#libraryFilterList").find("input").val()), u)
            u.permanent(), u = null;
        else {
            $.mobile.showPageLoadingMsg();
            var t = $("#planForm").serialize();
            $.post("/Portal/Plan/savePlan", t, r, "json")
        }
    }
}

function r(a) {
    $.mobile.hidePageLoadingMsg(), a.status ? (showSuccess("Save Book Success"), c.fire("closePanel")) : showError(a.info)
}

function n() {
    var a = !0, t = !1;
    return $form = $("#planForm"), $form.find(".required").each(function() {
        $(this).valid() || ($(this).parents("div.ui-input-text").addClass("error"), a = !1)
    }), $("#libraryFilterList input").val() || ($("#libraryFilterList").find("div").addClass("error"), a = !1), $form.find(".ui-input-text").each(function() {
        f.isScript($(this).val()) || ( a = !1, t = !0, "input" == this.tagName.toLowerCase() ? $(this).parent().addClass("error") : "textarea" == this.tagName.toLowerCase() && $(this).addClass("error"))
    }), t && showError("不能包含<>等特殊字符。"), a
}

function l(a, t) {
    var e = uploadOption;
    e.buttonText = "", "portrait" == t ? (e.buttonClass = "portraitWrap portraitUploadBg", e.width = 100, e.height = 130) : (e.buttonClass = "landscapeWrap landscapeUploadBg", e.width = 130, e.height = 100), e.fileType = ["jpg", "png", "jpeg"], e.uploadScript = "/Portal/File/uploadPhoto", e.onUploadComplete = function(e, o) {
        if (!o)
            return showError("Upload Failed"), !1;
        var i = JSON.parse(o);
        $("#uploadifive-" + a).removeClass("portraitUploadBg landscapeUploadBg").css("background-image", "url(" + i.filepath + ")"), "portrait" == t ? ($("#portraitCoverID").val(i.fileID), $("#portraitCover").val(i.filepath)) : ($("#landscapeCoverID").val(i.fileID), $("#landscapeCover").val(i.filepath))
    }, $("#" + a).uploadifive(e), $("#uploadifive-" + a).attr("title", "Upload File").css("cursor", "pointer")
}

function s() {
    $("#orientationImgWrap").on("tap", ".orientationImg", d), $("#savePlanBtn").on("click", i), $("#editBookBtn").on("click", p), $("#planForm").on("click", ".closeBtn", function() {
        c.fire("closePanel")
    })
}

function d(a) {
    var t = $(a.target), e = t.data("orientation");
    $("#orientationInput").val(e), t.data("selected") || (t.siblings("img").each(function() {
        $(this).attr("src", $(this).data("normalimg")).data("selected", !1)
    }), t.data("selected", !0).attr("src", t.data("selectimg")))
}

function p() {
    var a = $("#bookID").val();
    $.post("/Portal/Plan/getPlanByID", {
        planID : a
    }, function(a) {
        if ($.mobile.hidePageLoadingMsg(), a.status) {
            var t = $("#planForm"), e = a.data, o = e.portraitCover, i = e.landscapeCover;
            t.find("#issueNoLabel").text(e.issueNo), t.find("#landscapeCoverID").val(e.landscapeCoverID), t.find("#portraitCoverID").val(e.portraitCoverID), t.find("#landscapeCover").val(i), t.find("#portraitCover").val(o), t.find("#plan_issueID").val(e.issueID), t.find("#book").val(e.book), t.find("#orientationInput").val(e.orientation), t.find("#bookKicker").val(e.bookKicker), t.find("#plan_planID").val(e.id), t.find("#libraryFilter").val(e.libraryFilter), t.find("#libraryFilterList input").val(e.libraryFilter), t.find("#description").val(e.description), i && t.find("#uploadifive-uploadLandscapeCoverBtn").removeClass("landscapeUploadBg").css("background-image", "url(" + i + ")"), o && t.find("#uploadifive-uploadPortraitCoverBtn").removeClass("portraitUploadBg").css("background-image", "url(" + o + ")");
            var r;
            $(".orientationImg").each(function() {
                r = $(this), r.attr("src", r.data("normalimg")).data("selected", !1), r.data("orientation") == e.orientation && r.data("selected", !0).attr("src", r.data("selectimg"))
            })
        } else
            showError(a.info)
    }, "json")
}

var u, c = a("portal/base/middleware"), f = a("portal/base/util");
e.exports = {
    init : function() {
        l("uploadPortraitCoverBtn", "portrait"), l("uploadLandscapeCoverBtn", "landscape"), o(), s(), $("#planForm").validate({
            errorLabelContainer : $("#planForm div.errorWrap")
        })
    },
    createBook : function(a) {
        u = a
    },
    removeBook : function() {
        u && (u.destroy(), u = null)
    },
    resetBookForm : function() {
        var a = document.getElementById("planForm");
        a.reset(), $(a).find("form")[0].reset(), $("#libraryFilter").val(""), $("#filterAutocomplete").empty(), $(a).find("#portraitCoverID").val(""), $(a).find("#landscapeCoverID").val(""), $(a).find("#landscapeCover").val(""), $(a).find("#portraitCover").val(""), u = null
    }
}
```

}), define("portal/base/middleware", [], function(a, t) {
    var e = {};
    t.subscribe = function(a, t, o) {
        e[a] || (e[a] = {}), e[a] = {
            fn : t,
            arg : o
        }
    }, t.unsubscribe = function(a) {
        return e[a] && a ? e[a] ? (e[a] = {}, !0) : !1 : !1
    }, t.fire = function(a, t) {
        e[a] && e[a].fn(t, e[a].arg)
    }
}), define("portal/base/util", [], function(a, t, e) {
    e.exports = {
        isScript : function(a) {
            return !/[<>]/.test(a)
        },
        stopBubble : function(a) {
            a.preventDefault(), a.stopPropagation()
        },
        showMask : function() {
            var a = this;
            $("#maskLayer").show().on("mousedown touchstart", function(t) {
                a.stopBubble(t)
            })
        },
        TIPS : {
            timeout : "timeout",
            refresh : "refresh",
            timeoutInfo : "登陸超時，請重新登陸",
            deleteArticle : "當前Article已被刪除",
            conflict : "當前頁面已被更新，點擊'確定'刷新頁面，點擊'取消'繼續保存",
            deleteBook : "當前Book已被刪除，將返回App首頁"
        }
    }
});

应用到html中，虽然加载了也不报错，但是却未初始化。就好像是存在互相依赖关系，导致无法初始化的效果一样。但是这几个代码并没有互相依赖。不知道是哪里出错了。麻烦作者看下。非常感谢。

**Comment by edokeh** [comment]
你这么大段的代码我没法看啊
凭直觉，我觉得你是掉进这个坑里面了 https://github.com/seajs/seajs/issues/930
